# Generated by Django 3.2.9 on 2022-01-19 18:36

import AllUsers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(unique=True)),
                ('tutor_id', models.IntegerField(unique=True)),
                ('skill_id', models.IntegerField(unique=True)),
                ('admin_id', models.IntegerField(unique=True)),
                ('class_start_date', models.DateField()),
                ('skill_duration_left', models.IntegerField()),
                ('class_description', models.CharField(max_length=255)),
                ('rating_by_student', models.IntegerField()),
                ('feedback_in_words', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
                ('skill_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FuldemyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('DOB', models.DateField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to=AllUsers.models.user_directory_path)),
                ('CV', models.FileField(default='settings.MEDIA_ROOT/CV/Sourajyoti_Datta_CV.pdf', upload_to=AllUsers.models.CV_directory_path)),
                ('skills_text', models.CharField(default='', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('skills_present', models.ManyToManyField(blank=True, null=True, to='AllUsers.Skills')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
