# Generated by Django 3.2.9 on 2022-01-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeclasses',
            name='class_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
