# Generated by Django 3.2.9 on 2022-01-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0002_messagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeclasses',
            old_name='class_description',
            new_name='class_review',
        ),
        migrations.RenameField(
            model_name='activeclasses',
            old_name='skill_duration_left',
            new_name='student_id',
        ),
        migrations.RemoveField(
            model_name='activeclasses',
            name='admin_id',
        ),
        migrations.AlterField(
            model_name='activeclasses',
            name='skill_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activeclasses',
            name='tutor_id',
            field=models.IntegerField(),
        ),
    ]
