# Generated by Django 3.2.9 on 2022-01-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0002_fuldemyuser_skills_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuldemyuser',
            name='skills_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
