# Generated by Django 3.2.9 on 2022-01-03 21:22

import AllUsers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0002_fuldemyuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuldemyuser',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to=AllUsers.models.user_directory_path),
        ),
    ]
