# Generated by Django 3.2.9 on 2022-01-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0003_fuldemyuser_skills_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuldemyuser',
            name='skills_present',
            field=models.ManyToManyField(blank=True, null=True, to='AllUsers.Skills'),
        ),
    ]
