# Generated by Django 3.2.9 on 2022-01-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllUsers', '0004_auto_20220122_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeclasses',
            name='class_review',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activeclasses',
            name='feedback_in_words',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activeclasses',
            name='rating_by_student',
            field=models.IntegerField(null=True),
        ),
    ]
