# Generated by Django 3.2.9 on 2021-12-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_first_name', models.CharField(max_length=30)),
                ('tutor_last_name', models.CharField(max_length=30)),
                ('tutor_email', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
